<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Working with data | Data Processing in R, Lecture Notes</title>
  <meta name="description" content="Lecture notes on data processing in R." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Working with data | Data Processing in R, Lecture Notes" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Lecture notes on data processing in R." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Working with data | Data Processing in R, Lecture Notes" />
  
  <meta name="twitter:description" content="Lecture notes on data processing in R." />
  

<meta name="author" content="Pavel Logacev and Utku Türk" />


<meta name="date" content="2020-11-22" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="introR.html"/>
<link rel="next" href="a-first-plot.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Getting Started</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#initial-remarks"><i class="fa fa-check"></i><b>1.1</b> Initial Remarks</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#specific-useful-cheat-sheets-and-primers"><i class="fa fa-check"></i><b>1.2</b> Specific useful cheat sheets and primers</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#installing-and-setting-up-rstudio"><i class="fa fa-check"></i><b>1.3</b> Installing and Setting up RStudio</a><ul>
<li class="chapter" data-level="1.3.1" data-path="index.html"><a href="index.html#local-rstudio-installation"><i class="fa fa-check"></i><b>1.3.1</b> Local RStudio installation</a></li>
<li class="chapter" data-level="1.3.2" data-path="index.html"><a href="index.html#rstudio-cloud"><i class="fa fa-check"></i><b>1.3.2</b> RStudio Cloud</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#rstudio-interface"><i class="fa fa-check"></i><b>1.4</b> RStudio Interface</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#basics-of-the-rstudio-environment"><i class="fa fa-check"></i><b>1.5</b> Basics of the RStudio environment</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#special-blocks-in-the-following"><i class="fa fa-check"></i><b>1.6</b> Special blocks in the following</a></li>
<li class="chapter" data-level="1.7" data-path="index.html"><a href="index.html#lecture-notes-source-code"><i class="fa fa-check"></i><b>1.7</b> Lecture Notes Source Code</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introduction</a><ul>
<li class="chapter" data-level="2.1" data-path="intro.html"><a href="intro.html#introduction-to-r"><i class="fa fa-check"></i><b>2.1</b> Introduction to R</a></li>
<li class="chapter" data-level="2.2" data-path="intro.html"><a href="intro.html#the-basics"><i class="fa fa-check"></i><b>2.2</b> The Basics</a></li>
<li class="chapter" data-level="2.3" data-path="intro.html"><a href="intro.html#assignment"><i class="fa fa-check"></i><b>2.3</b> Assignment</a></li>
<li class="chapter" data-level="2.4" data-path="intro.html"><a href="intro.html#evaluation"><i class="fa fa-check"></i><b>2.4</b> Evaluation</a></li>
<li class="chapter" data-level="2.5" data-path="intro.html"><a href="intro.html#operators"><i class="fa fa-check"></i><b>2.5</b> Operators</a></li>
<li class="chapter" data-level="2.6" data-path="intro.html"><a href="intro.html#using-r-help"><i class="fa fa-check"></i><b>2.6</b> Using R Help</a></li>
<li class="chapter" data-level="2.7" data-path="intro.html"><a href="intro.html#data-types"><i class="fa fa-check"></i><b>2.7</b> Data Types</a></li>
<li class="chapter" data-level="2.8" data-path="intro.html"><a href="intro.html#determining-data-types"><i class="fa fa-check"></i><b>2.8</b> Determining Data Types</a></li>
<li class="chapter" data-level="2.9" data-path="intro.html"><a href="intro.html#packages"><i class="fa fa-check"></i><b>2.9</b> Packages</a></li>
<li class="chapter" data-level="2.10" data-path="intro.html"><a href="intro.html#plotting"><i class="fa fa-check"></i><b>2.10</b> Plotting</a></li>
<li class="chapter" data-level="2.11" data-path="intro.html"><a href="intro.html#example-putting-it-all-and-some-more-together"><i class="fa fa-check"></i><b>2.11</b> Example: Putting it all (and some more) together</a><ul>
<li class="chapter" data-level="2.11.1" data-path="intro.html"><a href="intro.html#how-much-would-other-coffee-sizes-cost-if-starbucks-introduced-them"><i class="fa fa-check"></i><b>2.11.1</b> How much would other coffee sizes cost if Starbucks introduced them?</a></li>
<li class="chapter" data-level="2.11.2" data-path="intro.html"><a href="intro.html#how-much-would-other-coffee-sizes-cost-if-starbucks-introduced-them-a-second-attempt"><i class="fa fa-check"></i><b>2.11.2</b> How much would other coffee sizes cost if Starbucks introduced them? A second attempt</a></li>
</ul></li>
<li class="chapter" data-level="2.12" data-path="intro.html"><a href="intro.html#operators-and-functions-in-this-section"><i class="fa fa-check"></i><b>2.12</b> Operators and functions in this section</a><ul>
<li class="chapter" data-level="2.12.1" data-path="intro.html"><a href="intro.html#operators-1"><i class="fa fa-check"></i><b>2.12.1</b> Operators</a></li>
<li class="chapter" data-level="2.12.2" data-path="intro.html"><a href="intro.html#functions"><i class="fa fa-check"></i><b>2.12.2</b> Functions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="introR.html"><a href="introR.html"><i class="fa fa-check"></i><b>3</b> Data Structures</a><ul>
<li class="chapter" data-level="3.1" data-path="introR.html"><a href="introR.html#recap-data-types-in-r"><i class="fa fa-check"></i><b>3.1</b> Recap: Data Types in R</a></li>
<li class="chapter" data-level="3.2" data-path="introR.html"><a href="introR.html#data-structures-in-r"><i class="fa fa-check"></i><b>3.2</b> Data Structures in R</a></li>
<li class="chapter" data-level="3.3" data-path="introR.html"><a href="introR.html#vectors"><i class="fa fa-check"></i><b>3.3</b> Vectors</a><ul>
<li class="chapter" data-level="3.3.1" data-path="introR.html"><a href="introR.html#what-are-vectors-good-for"><i class="fa fa-check"></i><b>3.3.1</b> What are vectors good for?</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="introR.html"><a href="introR.html#data-frames"><i class="fa fa-check"></i><b>3.4</b> Data Frames</a></li>
<li class="chapter" data-level="3.5" data-path="introR.html"><a href="introR.html#working-with-data-frames"><i class="fa fa-check"></i><b>3.5</b> Working with data frames</a></li>
<li class="chapter" data-level="3.6" data-path="introR.html"><a href="introR.html#functions-in-this-section"><i class="fa fa-check"></i><b>3.6</b> Functions in this section</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="working-with-data.html"><a href="working-with-data.html"><i class="fa fa-check"></i><b>4</b> Working with data</a><ul>
<li class="chapter" data-level="4.1" data-path="working-with-data.html"><a href="working-with-data.html#summarizing-data"><i class="fa fa-check"></i><b>4.1</b> Summarizing data</a><ul>
<li class="chapter" data-level="4.1.1" data-path="working-with-data.html"><a href="working-with-data.html#now-step-by-step"><i class="fa fa-check"></i><b>4.1.1</b> Now, step by step</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="working-with-data.html"><a href="working-with-data.html#working-with-dplyr"><i class="fa fa-check"></i><b>4.2</b> Working with dplyr</a></li>
<li class="chapter" data-level="4.3" data-path="working-with-data.html"><a href="working-with-data.html#pipes"><i class="fa fa-check"></i><b>4.3</b> Pipes</a><ul>
<li class="chapter" data-level="4.3.1" data-path="working-with-data.html"><a href="working-with-data.html#the-problem"><i class="fa fa-check"></i><b>4.3.1</b> The problem</a></li>
<li class="chapter" data-level="4.3.2" data-path="working-with-data.html"><a href="working-with-data.html#pipes-1"><i class="fa fa-check"></i><b>4.3.2</b> Pipes</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="working-with-data.html"><a href="working-with-data.html#functions-used-in-this-section"><i class="fa fa-check"></i><b>4.4</b> Functions used in this section</a><ul>
<li class="chapter" data-level="4.4.1" data-path="working-with-data.html"><a href="working-with-data.html#operators-2"><i class="fa fa-check"></i><b>4.4.1</b> Operators</a></li>
<li class="chapter" data-level="4.4.2" data-path="working-with-data.html"><a href="working-with-data.html#functions-1"><i class="fa fa-check"></i><b>4.4.2</b> Functions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="a-first-plot.html"><a href="a-first-plot.html"><i class="fa fa-check"></i><b>5</b> A first plot</a><ul>
<li class="chapter" data-level="5.1" data-path="a-first-plot.html"><a href="a-first-plot.html#the-basics-of-ggplot2"><i class="fa fa-check"></i><b>5.1</b> The basics of ggplot2</a></li>
<li class="chapter" data-level="5.2" data-path="a-first-plot.html"><a href="a-first-plot.html#the-basics-of-ggplot2-1"><i class="fa fa-check"></i><b>5.2</b> The basics of ggplot2</a></li>
<li class="chapter" data-level="5.3" data-path="a-first-plot.html"><a href="a-first-plot.html#using-lines-in-plots"><i class="fa fa-check"></i><b>5.3</b> Using lines in plots</a></li>
<li class="chapter" data-level="5.4" data-path="a-first-plot.html"><a href="a-first-plot.html#color-and-fill"><i class="fa fa-check"></i><b>5.4</b> Color and fill</a></li>
<li class="chapter" data-level="5.5" data-path="a-first-plot.html"><a href="a-first-plot.html#grouping-and-facets"><i class="fa fa-check"></i><b>5.5</b> Grouping and facets</a></li>
<li class="chapter" data-level="5.6" data-path="a-first-plot.html"><a href="a-first-plot.html#grouping-and-facets-1"><i class="fa fa-check"></i><b>5.6</b> Grouping and facets</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="functions-2.html"><a href="functions-2.html"><i class="fa fa-check"></i><b>6</b> Functions</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Processing in R, Lecture Notes</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="working-with-data" class="section level1">
<h1><span class="header-section-number">Chapter 4</span> Working with data</h1>
<p>(22 November, 2020, 05:22)</p>
<style type="text/css">
.r-output {
  font-weight: bold;
}
.function {
  background-color: lightgrey;
  padding: 0.5em 0.5em 0.5em 4em;
  border: 1px solid black;
}
</style>
<ul>
<li><p>Today, let’s work with realistic data. In order to access it, we’ll need to load the R package <code>languageR</code>. It provides a number of interesting data sets related to language.</p></li>
<li><p>You may need to install it, if it’s not already installed:</p></li>
</ul>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="working-with-data.html#cb1-1"></a><span class="kw">install.packages</span>(<span class="st">&quot;languageR&quot;</span>)</span></code></pre></div>
<ul>
<li>Let’s load the package and take a look at the data set.</li>
</ul>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="working-with-data.html#cb2-1"></a><span class="kw">library</span>(languageR)</span>
<span id="cb2-2"><a href="working-with-data.html#cb2-2"></a></span>
<span id="cb2-3"><a href="working-with-data.html#cb2-3"></a><span class="kw">head</span>(dativeSimplified)</span></code></pre></div>
<pre class="r-output"><code>##   RealizationOfRec  Verb AnimacyOfRec AnimacyOfTheme LengthOfTheme
## 1               NP  feed      animate      inanimate      2.639057
## 2               NP  give      animate      inanimate      1.098612
## 3               NP  give      animate      inanimate      2.564949
## 4               NP  give      animate      inanimate      1.609438
## 5               NP offer      animate      inanimate      1.098612
## 6               NP  give      animate      inanimate      1.386294</code></pre>
<ul>
<li>This data set happens to be documented. Let’s take a look at its description. (You can also see it <a href="https://rdrr.io/cran/languageR/man/dativeSimplified.html">here</a>. )</li>
</ul>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="working-with-data.html#cb4-1"></a><span class="kw">help</span>(<span class="st">&quot;dativeSimplified&quot;</span>)</span>
<span id="cb4-2"><a href="working-with-data.html#cb4-2"></a><span class="co"># or we can use ?dativeSimplified</span></span></code></pre></div>
<ul>
<li>The dative alternation in English is the alternation between (1) and (2). Both are grammatical and have the same truth conditions.</li>
<li>Bresnan et al. (2007) used this data to determine which factors affect the choice between (1) and (2).</li>
</ul>
<ol style="list-style-type: decimal">
<li>Peter gave Mary the book.</li>
<li>Peter gave the book to Mary.</li>
</ol>
<ul>
<li>Let’s take a look at a few rows chosen at random to get a look at a more representative sample …</li>
</ul>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="working-with-data.html#cb5-1"></a><span class="co"># store all possible row indices in a vector</span></span>
<span id="cb5-2"><a href="working-with-data.html#cb5-2"></a>indices_all &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(dativeSimplified)</span>
<span id="cb5-3"><a href="working-with-data.html#cb5-3"></a></span>
<span id="cb5-4"><a href="working-with-data.html#cb5-4"></a><span class="co"># set the random seed to make the results reproducible</span></span>
<span id="cb5-5"><a href="working-with-data.html#cb5-5"></a><span class="kw">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb5-6"><a href="working-with-data.html#cb5-6"></a></span>
<span id="cb5-7"><a href="working-with-data.html#cb5-7"></a><span class="co"># choose 10 such numbers at random without replacement</span></span>
<span id="cb5-8"><a href="working-with-data.html#cb5-8"></a>indices_random &lt;-<span class="st"> </span><span class="kw">sample</span>(indices_all, <span class="dt">size =</span> <span class="dv">10</span>)</span>
<span id="cb5-9"><a href="working-with-data.html#cb5-9"></a></span>
<span id="cb5-10"><a href="working-with-data.html#cb5-10"></a><span class="co"># use them to index the data frame to get the corresponding rows</span></span>
<span id="cb5-11"><a href="working-with-data.html#cb5-11"></a>dativeSimplified[indices_random,]</span></code></pre></div>
<pre class="r-output"><code>##     RealizationOfRec  Verb AnimacyOfRec AnimacyOfTheme LengthOfTheme
## 415               NP  give    inanimate      inanimate     1.7917595
## 463               NP grant      animate      inanimate     1.0986123
## 179               NP grant      animate      inanimate     2.3978953
## 526               NP  give      animate      inanimate     2.5649494
## 195               NP  tell      animate      inanimate     3.2580965
## 818               PP  give      animate      inanimate     0.0000000
## 118               NP   pay      animate      inanimate     0.6931472
## 299               NP  hand      animate      inanimate     0.6931472
## 229               NP  give    inanimate      inanimate     1.6094379
## 244               NP  wish      animate      inanimate     1.0986123</code></pre>
<ul>
<li>The above code works because rows and columns of data frames can be selected (<em>‘indexed’</em>)
<ul>
<li><code>df[row_indices, ]</code> selects rows <span class="math inline">\(-\)</span> <code>df[, col_indices]</code> selects columns</li>
<li><code>df[row_indices, col_indices]</code> selectes rows and columns</li>
<li>This works with row and column names, as well as indices.</li>
</ul></li>
</ul>
<div id="summarizing-data" class="section level2">
<h2><span class="header-section-number">4.1</span> Summarizing data</h2>
<ul>
<li>Let’s take a look at the percentages of NP realizations of the recipient by animacy of theme.</li>
</ul>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="working-with-data.html#cb7-1"></a><span class="co"># load the package dplyr to access the group_by/summarize functions</span></span>
<span id="cb7-2"><a href="working-with-data.html#cb7-2"></a><span class="kw">library</span>(dplyr)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="working-with-data.html#cb11-1"></a><span class="co"># let&#39;s take a look at the key dependent variable </span></span>
<span id="cb11-2"><a href="working-with-data.html#cb11-2"></a><span class="kw">unique</span>(dativeSimplified<span class="op">$</span>RealizationOfRec)</span></code></pre></div>
<pre class="r-output"><code>## [1] NP PP
## Levels: NP PP</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="working-with-data.html#cb13-1"></a><span class="co"># now, compute the percentages (perc_NP) and the number of observations in each subset</span></span>
<span id="cb13-2"><a href="working-with-data.html#cb13-2"></a>dativeSimplified <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb13-3"><a href="working-with-data.html#cb13-3"></a><span class="st">  </span><span class="kw">group_by</span>(AnimacyOfRec) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb13-4"><a href="working-with-data.html#cb13-4"></a><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">summarize</span>(<span class="dt">perc_NP =</span> <span class="kw">mean</span>(RealizationOfRec <span class="op">==</span><span class="st"> &quot;NP&quot;</span>), </span>
<span id="cb13-5"><a href="working-with-data.html#cb13-5"></a>                   <span class="dt">N =</span> <span class="kw">n</span>()</span>
<span id="cb13-6"><a href="working-with-data.html#cb13-6"></a>                  )</span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre class="r-output"><code>## # A tibble: 2 x 3
##   AnimacyOfRec perc_NP     N
##   &lt;fct&gt;          &lt;dbl&gt; &lt;int&gt;
## 1 animate        0.634   822
## 2 inanimate      0.420    81</code></pre>
<ul>
<li>What does this result say?</li>
<li>We can translate the first row of the dataframe to English as the following: “The percentage of NP realizations when the recipient is animate is 63.4% and there are 822 rows where the recipient is animate.”</li>
</ul>
<div id="now-step-by-step" class="section level3">
<h3><span class="header-section-number">4.1.1</span> Now, step by step</h3>
<ul>
<li><p>Wow, that was easy. …</p></li>
<li><p>But let’s break down the computations into their elementary parts and take look at the logic.</p></li>
<li><p>First, we’ll need to add a column which we can later use to compute the percentage of NP realizations.</p></li>
</ul>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="working-with-data.html#cb16-1"></a><span class="co"># first, let&#39;s create a new column encoding whether RealizationOfRec is &#39;NP&#39;</span></span>
<span id="cb16-2"><a href="working-with-data.html#cb16-2"></a><span class="co"># When the recipient is realized as an NP, this function will put a 1 in our new column.</span></span>
<span id="cb16-3"><a href="working-with-data.html#cb16-3"></a>dativeSimplified<span class="op">$</span>is_realization_NP &lt;-<span class="st"> </span><span class="kw">as.integer</span>( dativeSimplified<span class="op">$</span>RealizationOfRec <span class="op">==</span><span class="st"> &quot;NP&quot;</span> )</span></code></pre></div>
<ul>
<li>Take a subset of the data frame where AnimacyOfRec equals “animate” (note the <code>==</code>!).</li>
<li>For this, we can use <code>subset()</code> function. It takes a data frame and a condition for subsetting.</li>
</ul>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="working-with-data.html#cb17-1"></a><span class="co"># take a look at the values that can occur in this columns</span></span>
<span id="cb17-2"><a href="working-with-data.html#cb17-2"></a><span class="kw">unique</span>(dativeSimplified<span class="op">$</span>AnimacyOfRec)</span></code></pre></div>
<pre class="r-output"><code>## [1] animate   inanimate
## Levels: animate inanimate</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="working-with-data.html#cb19-1"></a><span class="co"># take two subsets corresponding to the values we determined above</span></span>
<span id="cb19-2"><a href="working-with-data.html#cb19-2"></a>df_animate &lt;-<span class="st"> </span><span class="kw">subset</span>(dativeSimplified, AnimacyOfRec <span class="op">==</span><span class="st"> &quot;animate&quot;</span>)</span>
<span id="cb19-3"><a href="working-with-data.html#cb19-3"></a>df_inanimate &lt;-<span class="st"> </span><span class="kw">subset</span>(dativeSimplified, AnimacyOfRec <span class="op">==</span><span class="st"> &quot;inanimate&quot;</span>)</span></code></pre></div>
<ul>
<li>Compute the average of the column <code>is_realization_NP</code> in each data frame, as well as the number of rows in it.</li>
<li>Then, put them together in a data frame.</li>
</ul>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="working-with-data.html#cb20-1"></a><span class="co"># compute the percentage of NP realizations </span></span>
<span id="cb20-2"><a href="working-with-data.html#cb20-2"></a>perc_NP_animate =<span class="st"> </span><span class="kw">mean</span>(df_animate<span class="op">$</span>is_realization_NP)</span>
<span id="cb20-3"><a href="working-with-data.html#cb20-3"></a></span>
<span id="cb20-4"><a href="working-with-data.html#cb20-4"></a><span class="co"># compute the percentage of NP realizations </span></span>
<span id="cb20-5"><a href="working-with-data.html#cb20-5"></a>N_animate =<span class="st"> </span><span class="kw">nrow</span>(df_animate)</span>
<span id="cb20-6"><a href="working-with-data.html#cb20-6"></a></span>
<span id="cb20-7"><a href="working-with-data.html#cb20-7"></a><span class="co"># bind to data frame</span></span>
<span id="cb20-8"><a href="working-with-data.html#cb20-8"></a>(res_animate &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">AnimacyOfRec =</span> <span class="st">&quot;animate&quot;</span>, <span class="dt">perc_NP =</span> perc_NP_animate, <span class="dt">N=</span>N_animate))</span></code></pre></div>
<pre class="r-output"><code>##   AnimacyOfRec perc_NP   N
## 1      animate 0.63382 822</code></pre>
<ul>
<li>Now, do the same for inanimates.</li>
</ul>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="working-with-data.html#cb22-1"></a>perc_NP_inanimate =<span class="st"> </span><span class="kw">mean</span>(df_inanimate<span class="op">$</span>is_realization_NP)</span>
<span id="cb22-2"><a href="working-with-data.html#cb22-2"></a>N_inanimate =<span class="st"> </span><span class="kw">nrow</span>(df_inanimate)</span>
<span id="cb22-3"><a href="working-with-data.html#cb22-3"></a>(res_inanimate &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">AnimacyOfRec =</span> <span class="st">&quot;inanimate&quot;</span>, <span class="dt">perc_NP =</span> perc_NP_animate, <span class="dt">N=</span>N_animate))</span></code></pre></div>
<pre class="r-output"><code>##   AnimacyOfRec perc_NP   N
## 1    inanimate 0.63382 822</code></pre>
<ul>
<li>Now, bind the results into a single data frame, which we can use for plotting, creating tables, etc.</li>
</ul>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="working-with-data.html#cb24-1"></a>res &lt;-<span class="st"> </span><span class="kw">rbind</span>(res_animate, res_inanimate)</span>
<span id="cb24-2"><a href="working-with-data.html#cb24-2"></a>res</span></code></pre></div>
<pre class="r-output"><code>##   AnimacyOfRec perc_NP   N
## 1      animate 0.63382 822
## 2    inanimate 0.63382 822</code></pre>
<ul>
<li>Puuuuuh. That was tedious.</li>
<li>The disadvantages of the <code>subset</code>-approach are:
<ul>
<li>Values of ‘game’ need to be known, and so the code needs to be adjusted to the contents of the dataset</li>
<li>Much less tractable for more grouping variables</li>
<li>Better options are available</li>
</ul></li>
</ul>
</div>
</div>
<div id="working-with-dplyr" class="section level2">
<h2><span class="header-section-number">4.2</span> Working with dplyr</h2>
<ul>
<li>The package <em>dplyr</em> (<a href="http://github.com/rstudio/cheatsheets/raw/master/data-transformation.pdf">cheat sheet</a>) provides a set of functions for working with data frames.</li>
<li>Some of functions don’t perform a noticeable action, while others reshape data frames or create new ones (the latter are called ‘verbs’)</li>
</ul>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="working-with-data.html#cb26-1"></a><span class="kw">library</span>(dplyr)</span></code></pre></div>
<ul>
<li><code>arrange()</code> sorts the data frame by one or several columns</li>
<li>By default, it does so in ascending order.</li>
</ul>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="working-with-data.html#cb27-1"></a><span class="kw">arrange</span>(dative[<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>,], LengthOfTheme)</span></code></pre></div>
<pre class="r-output"><code>##    Speaker Modality  Verb SemanticClass LengthOfRecipient AnimacyOfRec
## 8     &lt;NA&gt;  written bring             a                 1      animate
## 10    &lt;NA&gt;  written  give             a                 1      animate
## 2     &lt;NA&gt;  written  give             a                 2      animate
## 5     &lt;NA&gt;  written offer             c                 2      animate
## 6     &lt;NA&gt;  written  give             a                 2      animate
## 7     &lt;NA&gt;  written   pay             t                 2      animate
## 4     &lt;NA&gt;  written  give             a                 1      animate
## 9     &lt;NA&gt;  written teach             a                 1      animate
## 3     &lt;NA&gt;  written  give             a                 1      animate
## 1     &lt;NA&gt;  written  feed             t                 1      animate
##    DefinOfRec   PronomOfRec LengthOfTheme AnimacyOfTheme DefinOfTheme
## 8    definite    pronominal             1      inanimate   indefinite
## 10   definite    pronominal             2      inanimate   indefinite
## 2    definite nonpronominal             3      inanimate   indefinite
## 5    definite nonpronominal             3      inanimate     definite
## 6    definite nonpronominal             4      inanimate   indefinite
## 7    definite nonpronominal             4      inanimate   indefinite
## 4    definite    pronominal             5      inanimate   indefinite
## 9    definite    pronominal            11      inanimate   indefinite
## 3    definite nonpronominal            13      inanimate     definite
## 1    definite    pronominal            14      inanimate   indefinite
##    PronomOfTheme RealizationOfRecipient AccessOfRec AccessOfTheme
## 8  nonpronominal                     NP       given           new
## 10 nonpronominal                     NP       given    accessible
## 2  nonpronominal                     NP       given           new
## 5  nonpronominal                     NP       given           new
## 6  nonpronominal                     NP       given           new
## 7  nonpronominal                     NP       given           new
## 4  nonpronominal                     NP       given           new
## 9  nonpronominal                     NP       given    accessible
## 3  nonpronominal                     NP       given           new
## 1  nonpronominal                     NP       given           new</code></pre>
<ul>
<li>The modifier <code>desc()</code> switches <code>arrange()</code> to an decending order.</li>
</ul>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="working-with-data.html#cb29-1"></a><span class="kw">arrange</span>(dative[<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>,], <span class="kw">desc</span>(LengthOfTheme))</span></code></pre></div>
<pre class="r-output"><code>##    Speaker Modality  Verb SemanticClass LengthOfRecipient AnimacyOfRec
## 1     &lt;NA&gt;  written  feed             t                 1      animate
## 3     &lt;NA&gt;  written  give             a                 1      animate
## 9     &lt;NA&gt;  written teach             a                 1      animate
## 4     &lt;NA&gt;  written  give             a                 1      animate
## 6     &lt;NA&gt;  written  give             a                 2      animate
## 7     &lt;NA&gt;  written   pay             t                 2      animate
## 2     &lt;NA&gt;  written  give             a                 2      animate
## 5     &lt;NA&gt;  written offer             c                 2      animate
## 10    &lt;NA&gt;  written  give             a                 1      animate
## 8     &lt;NA&gt;  written bring             a                 1      animate
##    DefinOfRec   PronomOfRec LengthOfTheme AnimacyOfTheme DefinOfTheme
## 1    definite    pronominal            14      inanimate   indefinite
## 3    definite nonpronominal            13      inanimate     definite
## 9    definite    pronominal            11      inanimate   indefinite
## 4    definite    pronominal             5      inanimate   indefinite
## 6    definite nonpronominal             4      inanimate   indefinite
## 7    definite nonpronominal             4      inanimate   indefinite
## 2    definite nonpronominal             3      inanimate   indefinite
## 5    definite nonpronominal             3      inanimate     definite
## 10   definite    pronominal             2      inanimate   indefinite
## 8    definite    pronominal             1      inanimate   indefinite
##    PronomOfTheme RealizationOfRecipient AccessOfRec AccessOfTheme
## 1  nonpronominal                     NP       given           new
## 3  nonpronominal                     NP       given           new
## 9  nonpronominal                     NP       given    accessible
## 4  nonpronominal                     NP       given           new
## 6  nonpronominal                     NP       given           new
## 7  nonpronominal                     NP       given           new
## 2  nonpronominal                     NP       given           new
## 5  nonpronominal                     NP       given           new
## 10 nonpronominal                     NP       given    accessible
## 8  nonpronominal                     NP       given           new</code></pre>
<ul>
<li><code>select()</code> keeps <em>only</em> the pre-specified columns from the data frame</li>
</ul>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="working-with-data.html#cb31-1"></a><span class="co"># Let&#39;s assume we do not care about everything within the dative data frame.</span></span>
<span id="cb31-2"><a href="working-with-data.html#cb31-2"></a><span class="co"># What is important for us is Modality, AnimacyOfTheme, LengthOfTheme, and RealizationOfRecipient.</span></span>
<span id="cb31-3"><a href="working-with-data.html#cb31-3"></a></span>
<span id="cb31-4"><a href="working-with-data.html#cb31-4"></a>df &lt;-<span class="st"> </span><span class="kw">select</span>(dative, Modality, AnimacyOfTheme, LengthOfTheme, RealizationOfRecipient)</span>
<span id="cb31-5"><a href="working-with-data.html#cb31-5"></a><span class="kw">head</span>(df)</span></code></pre></div>
<pre class="r-output"><code>##   Modality AnimacyOfTheme LengthOfTheme RealizationOfRecipient
## 1  written      inanimate            14                     NP
## 2  written      inanimate             3                     NP
## 3  written      inanimate            13                     NP
## 4  written      inanimate             5                     NP
## 5  written      inanimate             3                     NP
## 6  written      inanimate             4                     NP</code></pre>
<ul>
<li><code>select()</code> can also <em>deselect</em> columns. Let’s assume that we changed our mind and do not want to work with the Modality column.</li>
<li>Similar to the indices, minus symbol <code>-</code> deselects the specified column(s).</li>
</ul>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="working-with-data.html#cb33-1"></a>df &lt;-<span class="st"> </span><span class="kw">select</span>(df, <span class="op">-</span>Modality)</span>
<span id="cb33-2"><a href="working-with-data.html#cb33-2"></a><span class="kw">head</span>(df)</span></code></pre></div>
<pre class="r-output"><code>##   AnimacyOfTheme LengthOfTheme RealizationOfRecipient
## 1      inanimate            14                     NP
## 2      inanimate             3                     NP
## 3      inanimate            13                     NP
## 4      inanimate             5                     NP
## 5      inanimate             3                     NP
## 6      inanimate             4                     NP</code></pre>
<ul>
<li><code>left_join()</code> merges two data frames by common columns. This is very useful when data comes from two different sources.</li>
</ul>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="working-with-data.html#cb35-1"></a>df1 &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">name =</span> <span class="kw">c</span>(<span class="st">&quot;Peter&quot;</span>, <span class="st">&quot;Mary&quot;</span>, <span class="st">&quot;Susy&quot;</span>, <span class="st">&quot;John&quot;</span>), <span class="dt">n_apples =</span> <span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">1</span>))</span>
<span id="cb35-2"><a href="working-with-data.html#cb35-2"></a>df2 &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">name =</span> <span class="kw">c</span>(<span class="st">&quot;Peter&quot;</span>, <span class="st">&quot;Mary&quot;</span>, <span class="st">&quot;Susy&quot;</span>), <span class="dt">n_oranges =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">20</span>,<span class="dv">0</span>))</span>
<span id="cb35-3"><a href="working-with-data.html#cb35-3"></a>df &lt;-<span class="st"> </span>dplyr<span class="op">::</span><span class="kw">left_join</span>(df1, df2)</span></code></pre></div>
<pre><code>## Joining, by = &quot;name&quot;</code></pre>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="working-with-data.html#cb37-1"></a>df<span class="op">$</span>n_fruit &lt;-<span class="st"> </span>df<span class="op">$</span>n_apples <span class="op">+</span><span class="st"> </span>df<span class="op">$</span>n_oranges</span></code></pre></div>
<ul>
<li><code>sample_n()</code> shows a few random rows from the data frame</li>
</ul>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="working-with-data.html#cb38-1"></a><span class="kw">sample_n</span>(dativeSimplified, <span class="dv">10</span>)</span></code></pre></div>
<pre class="r-output"><code>##     RealizationOfRec  Verb AnimacyOfRec AnimacyOfTheme LengthOfTheme
## 14                NP  give      animate      inanimate     0.6931472
## 374               NP  sell      animate      inanimate     0.0000000
## 665               PP  give      animate      inanimate     1.6094379
## 602               PP   pay      animate      inanimate     1.3862944
## 603               PP offer    inanimate      inanimate     1.9459101
## 768               PP  sell      animate      inanimate     1.6094379
## 709               PP  give      animate      inanimate     0.0000000
## 91                NP  give      animate      inanimate     2.0794415
## 348               NP  cost      animate      inanimate     0.6931472
## 649               PP  sell      animate      inanimate     1.0986123
##     is_realization_NP
## 14                  1
## 374                 1
## 665                 0
## 602                 0
## 603                 0
## 768                 0
## 709                 0
## 91                  1
## 348                 1
## 649                 0</code></pre>
<ul>
<li><code>group_by()</code> and <code>ungroup()</code> add and remove information about grouping variables</li>
</ul>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="working-with-data.html#cb40-1"></a><span class="co"># let&#39;s &#39;group&#39; a small subset of the gambling data frame by game</span></span>
<span id="cb40-2"><a href="working-with-data.html#cb40-2"></a><span class="kw">group_by</span>(dativeSimplified[<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>,], RealizationOfRec) </span></code></pre></div>
<pre class="r-output"><code>## # A tibble: 2 x 6
## # Groups:   RealizationOfRec [1]
##   RealizationOfRec Verb  AnimacyOfRec AnimacyOfTheme LengthOfTheme
##   &lt;fct&gt;            &lt;fct&gt; &lt;fct&gt;        &lt;fct&gt;                  &lt;dbl&gt;
## 1 NP               feed  animate      inanimate               2.64
## 2 NP               give  animate      inanimate               1.10
## # ... with 1 more variable: is_realization_NP &lt;int&gt;</code></pre>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="working-with-data.html#cb42-1"></a><span class="co"># let&#39;s compare to the original data frame</span></span>
<span id="cb42-2"><a href="working-with-data.html#cb42-2"></a>dativeSimplified[<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>,]</span></code></pre></div>
<pre class="r-output"><code>##   RealizationOfRec Verb AnimacyOfRec AnimacyOfTheme LengthOfTheme
## 1               NP feed      animate      inanimate      2.639057
## 2               NP give      animate      inanimate      1.098612
##   is_realization_NP
## 1                 1
## 2                 1</code></pre>
<ul>
<li>Data frames need to be grouped for use with <code>summarize()</code> and <code>mutate()</code>.</li>
</ul>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="working-with-data.html#cb44-1"></a><span class="co"># let&#39;s group the dativeSimplified data frame </span></span>
<span id="cb44-2"><a href="working-with-data.html#cb44-2"></a>dativeSimplified_grouped &lt;-<span class="st"> </span><span class="kw">group_by</span>(dativeSimplified, Verb)</span></code></pre></div>
<ul>
<li><code>summarize()</code> is a complex function that does multiples things in a single instance.</li>
<li>Firstly, it divides a grouped data frame into subsets, with <em>each</em> subset corresponding to one value of the grouping variable (or a combination of values for several grouping variables).</li>
<li>Second, it computes one or several values we specify on each such subset.</li>
<li>Lastly, it creates a new data frame and puts everything together. The first column of this new data frame consists of levels of our grouping variable. In the following columns, the <code>summarize()</code> function prints the results of the computations we have specified.</li>
<li>Try to guess the result of the following code. What will you see as an output? What will be the name of the columns?</li>
</ul>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="working-with-data.html#cb45-1"></a><span class="co"># summarize several variables</span></span>
<span id="cb45-2"><a href="working-with-data.html#cb45-2"></a><span class="kw">summarize</span>(dativeSimplified_grouped, </span>
<span id="cb45-3"><a href="working-with-data.html#cb45-3"></a>          <span class="dt">prop_NP =</span> <span class="kw">mean</span>(is_realization_NP),</span>
<span id="cb45-4"><a href="working-with-data.html#cb45-4"></a>          <span class="dt">prop_animate_rec =</span> <span class="kw">mean</span>( AnimacyOfRec <span class="op">==</span><span class="st"> &quot;animate&quot;</span> ),</span>
<span id="cb45-5"><a href="working-with-data.html#cb45-5"></a>          <span class="dt">prop_animate_theme =</span> <span class="kw">mean</span>( AnimacyOfTheme <span class="op">==</span><span class="st"> &quot;animate&quot;</span> ),</span>
<span id="cb45-6"><a href="working-with-data.html#cb45-6"></a>          <span class="dt">N =</span> <span class="kw">n</span>()</span>
<span id="cb45-7"><a href="working-with-data.html#cb45-7"></a>          )</span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre class="r-output"><code>## # A tibble: 65 x 5
##    Verb     prop_NP prop_animate_rec prop_animate_theme     N
##    &lt;fct&gt;      &lt;dbl&gt;            &lt;dbl&gt;              &lt;dbl&gt; &lt;int&gt;
##  1 accord     1                1                      0     1
##  2 allocate   0                0                      0     3
##  3 allow      1                0.833                  0     6
##  4 assess     1                1                      0     1
##  5 assure     1                1                      0     2
##  6 award      0.389            0.944                  0    18
##  7 bequeath   0                1                      0     1
##  8 bet        1                1                      0     1
##  9 bring      0.545            0.818                  0    11
## 10 carry      0                1                      0     1
## # ... with 55 more rows</code></pre>
<ul>
<li><code>summarize()</code> can use the results of previous computations specified within the same <code>summarize()</code> function.</li>
<li>In the code below, we first specify a column named <code>prop_NP</code>. Then, we use it to compute two other values named <code>prop_PP</code> and <code>how_many_NP_realizations</code>.</li>
</ul>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="working-with-data.html#cb48-1"></a><span class="co"># compute the averages of profit</span></span>
<span id="cb48-2"><a href="working-with-data.html#cb48-2"></a><span class="kw">summarize</span>(dativeSimplified_grouped, </span>
<span id="cb48-3"><a href="working-with-data.html#cb48-3"></a>          <span class="dt">prop_NP =</span> <span class="kw">mean</span>(is_realization_NP),</span>
<span id="cb48-4"><a href="working-with-data.html#cb48-4"></a>          <span class="dt">prop_PP =</span> <span class="dv">1</span><span class="op">-</span>prop_NP,</span>
<span id="cb48-5"><a href="working-with-data.html#cb48-5"></a>          <span class="dt">how_many_NP_realizations =</span> <span class="kw">ifelse</span>(prop_NP <span class="op">&gt;</span><span class="st"> </span><span class="fl">0.5</span>, <span class="st">&quot;a lot&quot;</span>, <span class="st">&quot;few&quot;</span>)</span>
<span id="cb48-6"><a href="working-with-data.html#cb48-6"></a>          )</span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre class="r-output"><code>## # A tibble: 65 x 4
##    Verb     prop_NP prop_PP how_many_NP_realizations
##    &lt;fct&gt;      &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;                   
##  1 accord     1       0     a lot                   
##  2 allocate   0       1     few                     
##  3 allow      1       0     a lot                   
##  4 assess     1       0     a lot                   
##  5 assure     1       0     a lot                   
##  6 award      0.389   0.611 few                     
##  7 bequeath   0       1     few                     
##  8 bet        1       0     a lot                   
##  9 bring      0.545   0.455 a lot                   
## 10 carry      0       1     few                     
## # ... with 55 more rows</code></pre>
<ul>
<li><p>The last line uses the function <code>ifelse(condition, value1, value2)</code>, which, for each element of the condition vector returns the corresponding element of the <code>value1</code> vector if the condition is true at that element, or an element of <code>vector2</code> otherwise.</p></li>
<li><p><code>mutate()</code> proceeds similarly to <code>summarize()</code> in dividing a grouped dataset into subsets, but instead of computing one or several values for each subset, it creates or modifies a column.</p></li>
<li><p>The main difference between <code>mutate()</code> and <code>summarize()</code> is the output. While <code>mutate()</code> keeps everything from the original data frame, <code>summarize()</code> creates a brand new data frame.</p></li>
<li><p>A very simple application of <code>mutate()</code> is to simply create a new column. In this case, we don’t even need to group.</p></li>
</ul>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="working-with-data.html#cb51-1"></a><span class="co"># these two lines performs exactly the same action, </span></span>
<span id="cb51-2"><a href="working-with-data.html#cb51-2"></a><span class="co"># except the latter stores the result in df </span></span>
<span id="cb51-3"><a href="working-with-data.html#cb51-3"></a>dativeSimplified<span class="op">$</span>is_realization_NP &lt;-<span class="st"> </span>(dativeSimplified<span class="op">$</span>RealizationOfRec <span class="op">==</span><span class="st"> &quot;NP&quot;</span> ) </span>
<span id="cb51-4"><a href="working-with-data.html#cb51-4"></a>df &lt;-<span class="st"> </span><span class="kw">mutate</span>(dativeSimplified, <span class="dt">is_realization_NP =</span> (RealizationOfRec <span class="op">==</span><span class="st"> &quot;NP&quot;</span>) )</span>
<span id="cb51-5"><a href="working-with-data.html#cb51-5"></a></span>
<span id="cb51-6"><a href="working-with-data.html#cb51-6"></a><span class="kw">head</span>(df, <span class="dv">2</span>)</span></code></pre></div>
<pre class="r-output"><code>##   RealizationOfRec Verb AnimacyOfRec AnimacyOfTheme LengthOfTheme
## 1               NP feed      animate      inanimate      2.639057
## 2               NP give      animate      inanimate      1.098612
##   is_realization_NP
## 1              TRUE
## 2              TRUE</code></pre>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="working-with-data.html#cb53-1"></a><span class="kw">head</span>(dativeSimplified, <span class="dv">2</span>)</span></code></pre></div>
<pre class="r-output"><code>##   RealizationOfRec Verb AnimacyOfRec AnimacyOfTheme LengthOfTheme
## 1               NP feed      animate      inanimate      2.639057
## 2               NP give      animate      inanimate      1.098612
##   is_realization_NP
## 1              TRUE
## 2              TRUE</code></pre>
</div>
<div id="pipes" class="section level2">
<h2><span class="header-section-number">4.3</span> Pipes</h2>
<div id="the-problem" class="section level3">
<h3><span class="header-section-number">4.3.1</span> The problem</h3>
<ul>
<li>The code below is really hard to read, even harder to maintain, and <code>dativeSimplified_grouped_by_AnimacyOfRec_and_AnimacyOfTheme</code> is a terribly long variable name.</li>
</ul>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="working-with-data.html#cb55-1"></a>dativeSimplified_grouped_by_AnimacyOfRec_and_AnimacyOfTheme &lt;-</span>
<span id="cb55-2"><a href="working-with-data.html#cb55-2"></a><span class="st">      </span><span class="kw">group_by</span>(dativeSimplified, AnimacyOfRec, AnimacyOfTheme)</span>
<span id="cb55-3"><a href="working-with-data.html#cb55-3"></a>df &lt;-<span class="st"> </span><span class="kw">summarize</span>(dativeSimplified_grouped_by_AnimacyOfRec_and_AnimacyOfTheme, </span>
<span id="cb55-4"><a href="working-with-data.html#cb55-4"></a>                  <span class="dt">perc_NP =</span> <span class="kw">mean</span>(RealizationOfRec <span class="op">==</span><span class="st"> &quot;NP&quot;</span>) )</span></code></pre></div>
<pre><code>## `summarise()` regrouping output by &#39;AnimacyOfRec&#39; (override with `.groups` argument)</code></pre>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="working-with-data.html#cb57-1"></a>df</span></code></pre></div>
<pre class="r-output"><code>## # A tibble: 4 x 3
## # Groups:   AnimacyOfRec [2]
##   AnimacyOfRec AnimacyOfTheme perc_NP
##   &lt;fct&gt;        &lt;fct&gt;            &lt;dbl&gt;
## 1 animate      animate          0.8  
## 2 animate      inanimate        0.633
## 3 inanimate    animate          1    
## 4 inanimate    inanimate        0.412</code></pre>
<ul>
<li>This alternative is also quite bad. To read this code, you need to know which bracket matches which other bracket.</li>
</ul>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="working-with-data.html#cb59-1"></a>df &lt;-<span class="st"> </span><span class="kw">summarize</span>(<span class="kw">group_by</span>(dativeSimplified, AnimacyOfRec, AnimacyOfTheme), </span>
<span id="cb59-2"><a href="working-with-data.html#cb59-2"></a>                  <span class="dt">perc_NP =</span> <span class="kw">mean</span>(RealizationOfRec <span class="op">==</span><span class="st"> &quot;NP&quot;</span>) )</span></code></pre></div>
<pre><code>## `summarise()` regrouping output by &#39;AnimacyOfRec&#39; (override with `.groups` argument)</code></pre>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="working-with-data.html#cb61-1"></a>df</span></code></pre></div>
<pre class="r-output"><code>## # A tibble: 4 x 3
## # Groups:   AnimacyOfRec [2]
##   AnimacyOfRec AnimacyOfTheme perc_NP
##   &lt;fct&gt;        &lt;fct&gt;            &lt;dbl&gt;
## 1 animate      animate          0.8  
## 2 animate      inanimate        0.633
## 3 inanimate    animate          1    
## 4 inanimate    inanimate        0.412</code></pre>
<ul>
<li>One nested function call may be OK. But try to read this.</li>
</ul>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="working-with-data.html#cb63-1"></a>df &lt;-<span class="st"> </span>dplyr<span class="op">::</span><span class="kw">summarize</span>(<span class="kw">group_by</span>(<span class="kw">mutate</span>(dativeSimplified, <span class="dt">long_theme =</span> <span class="kw">ifelse</span>(LengthOfTheme <span class="op">&gt;</span><span class="st"> </span><span class="fl">1.6</span>, <span class="st">&quot;long&quot;</span>, <span class="st">&quot;short&quot;</span>) ), long_theme),</span>
<span id="cb63-2"><a href="working-with-data.html#cb63-2"></a>              <span class="dt">perc_NP =</span> <span class="kw">mean</span>(RealizationOfRec <span class="op">==</span><span class="st"> &quot;NP&quot;</span>)</span>
<span id="cb63-3"><a href="working-with-data.html#cb63-3"></a>              )</span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<ul>
<li>Or consider this expression (<code>sqrt</code> is the square root.)</li>
</ul>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="working-with-data.html#cb65-1"></a><span class="kw">sqrt</span>(<span class="kw">divide_by</span>(<span class="kw">sum</span>(<span class="kw">divide_by</span>(<span class="dv">2</span>,<span class="dv">3</span>), <span class="kw">multiply_by</span>(<span class="dv">2</span>,<span class="dv">3</span>)), <span class="kw">sum</span>(<span class="dv">3</span>,<span class="dv">4</span>)))</span></code></pre></div>
<pre><code>## Error in divide_by(sum(divide_by(2, 3), multiply_by(2, 3)), sum(3, 4)): could not find function &quot;divide_by&quot;</code></pre>
<ul>
<li>Luckily, there is a better way to write these expressions.</li>
</ul>
</div>
<div id="pipes-1" class="section level3">
<h3><span class="header-section-number">4.3.2</span> Pipes</h3>
<ul>
<li>The problem is that we have too many levels of embedding.</li>
<li>In natural language we avoid multiple embeddings of that sort by making shorter sentences, and using anaphors to refer to previous discourse.</li>
<li>The packages <strong>dplyr</strong> and <strong>magrittr</strong> provide a limited version of such functionality, and we’ll need to use <strong>pipe</strong> operators (<code>%&gt;%</code> and <code>%&lt;&gt;%</code>) to link expressions with an ‘anaphoric dependency’.</li>
<li>Whenever you see <code>%&gt;%</code>, you can think about it as the following: “Take whatever is on the left side, and use it in the function that is on the right side.”</li>
</ul>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="working-with-data.html#cb67-1"></a><span class="kw">library</span>(dplyr)</span>
<span id="cb67-2"><a href="working-with-data.html#cb67-2"></a><span class="kw">library</span>(magrittr)</span>
<span id="cb67-3"><a href="working-with-data.html#cb67-3"></a><span class="co"># Typical notation. Read as &quot;Divide 10 by 2.&quot;</span></span>
<span id="cb67-4"><a href="working-with-data.html#cb67-4"></a><span class="kw">divide_by</span>(<span class="dv">10</span>, <span class="dv">2</span>)</span></code></pre></div>
<pre class="r-output"><code>## [1] 5</code></pre>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="working-with-data.html#cb69-1"></a><span class="co"># Equivalent pipe notation. Read as &quot;Take 10, and divide it by 2.&quot;</span></span>
<span id="cb69-2"><a href="working-with-data.html#cb69-2"></a><span class="dv">10</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">divide_by</span>(., <span class="dv">2</span>)</span></code></pre></div>
<pre class="r-output"><code>## [1] 5</code></pre>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="working-with-data.html#cb71-1"></a><span class="co"># Equivalent pipe notation. Read as &quot;Take 2, and divide 10 by it.&quot;</span></span>
<span id="cb71-2"><a href="working-with-data.html#cb71-2"></a><span class="dv">2</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">divide_by</span>(<span class="dv">10</span>, .)</span></code></pre></div>
<pre class="r-output"><code>## [1] 5</code></pre>
<ul>
<li>If the dot operator occurs in the first argument slot, it can be omitted. (R has pro-drop.)</li>
</ul>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="working-with-data.html#cb73-1"></a><span class="co"># pipe notation with omission of &#39;.&#39;</span></span>
<span id="cb73-2"><a href="working-with-data.html#cb73-2"></a><span class="dv">10</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">divide_by</span>(<span class="dv">2</span>)</span></code></pre></div>
<pre class="r-output"><code>## [1] 5</code></pre>
<ul>
<li>Let’s see how it can resolve the mess below. (Repetition of previous example.)</li>
</ul>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="working-with-data.html#cb75-1"></a>df &lt;-<span class="st"> </span><span class="kw">mutate</span>(<span class="kw">group_by</span>(dativeSimplified, AnimacyOfRec, AnimacyOfTheme), </span>
<span id="cb75-2"><a href="working-with-data.html#cb75-2"></a>                  <span class="dt">perc_NP =</span> <span class="kw">mean</span>(RealizationOfRec <span class="op">==</span><span class="st"> &quot;NP&quot;</span>) )</span>
<span id="cb75-3"><a href="working-with-data.html#cb75-3"></a>df</span></code></pre></div>
<pre class="r-output"><code>## # A tibble: 903 x 7
## # Groups:   AnimacyOfRec, AnimacyOfTheme [4]
##    RealizationOfRec Verb  AnimacyOfRec AnimacyOfTheme LengthOfTheme
##    &lt;fct&gt;            &lt;fct&gt; &lt;fct&gt;        &lt;fct&gt;                  &lt;dbl&gt;
##  1 NP               feed  animate      inanimate              2.64 
##  2 NP               give  animate      inanimate              1.10 
##  3 NP               give  animate      inanimate              2.56 
##  4 NP               give  animate      inanimate              1.61 
##  5 NP               offer animate      inanimate              1.10 
##  6 NP               give  animate      inanimate              1.39 
##  7 NP               pay   animate      inanimate              1.39 
##  8 NP               bring animate      inanimate              0    
##  9 NP               teach animate      inanimate              2.40 
## 10 NP               give  animate      inanimate              0.693
## # ... with 893 more rows, and 2 more variables: is_realization_NP &lt;lgl&gt;,
## #   perc_NP &lt;dbl&gt;</code></pre>
<ul>
<li>And here is the much more readable version of this code:</li>
</ul>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="working-with-data.html#cb77-1"></a>df &lt;-<span class="st">  </span>dativeSimplified <span class="op">%&gt;%</span></span>
<span id="cb77-2"><a href="working-with-data.html#cb77-2"></a><span class="st">          </span><span class="kw">mutate</span>(., <span class="dt">long_theme =</span> <span class="kw">ifelse</span>(LengthOfTheme <span class="op">&gt;</span><span class="st"> </span><span class="fl">1.6</span>, <span class="st">&quot;long&quot;</span>, <span class="st">&quot;short&quot;</span>) ) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb77-3"><a href="working-with-data.html#cb77-3"></a><span class="st">          </span><span class="kw">group_by</span>(., long_theme) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb77-4"><a href="working-with-data.html#cb77-4"></a><span class="st">          </span>dplyr<span class="op">::</span><span class="kw">summarize</span>(., <span class="dt">perc_NP =</span> <span class="kw">mean</span>(RealizationOfRec <span class="op">==</span><span class="st"> &quot;NP&quot;</span>) )</span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<ul>
<li>We don’t actually need the dot:</li>
</ul>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="working-with-data.html#cb79-1"></a>df &lt;-<span class="st">  </span>dativeSimplified <span class="op">%&gt;%</span></span>
<span id="cb79-2"><a href="working-with-data.html#cb79-2"></a><span class="st">          </span><span class="kw">mutate</span>(<span class="dt">long_theme =</span> <span class="kw">ifelse</span>(LengthOfTheme <span class="op">&gt;</span><span class="st"> </span><span class="fl">1.6</span>, <span class="st">&quot;long&quot;</span>, <span class="st">&quot;short&quot;</span>) ) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb79-3"><a href="working-with-data.html#cb79-3"></a><span class="st">          </span><span class="kw">group_by</span>(long_theme) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb79-4"><a href="working-with-data.html#cb79-4"></a><span class="st">          </span>dplyr<span class="op">::</span><span class="kw">summarize</span>(<span class="dt">perc_NP =</span> <span class="kw">mean</span>(RealizationOfRec <span class="op">==</span><span class="st"> &quot;NP&quot;</span>) )</span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<ul>
<li>The <code>%&lt;&gt;%</code> operator is a convenient combination of <code>%&gt;%</code> and <code>&lt;-</code> which you can use to directly modify an object.</li>
</ul>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="working-with-data.html#cb81-1"></a><span class="co"># load the package magrittr in order to access the assignment pipe operator</span></span>
<span id="cb81-2"><a href="working-with-data.html#cb81-2"></a><span class="kw">library</span>(magrittr)</span>
<span id="cb81-3"><a href="working-with-data.html#cb81-3"></a></span>
<span id="cb81-4"><a href="working-with-data.html#cb81-4"></a><span class="co"># create a vector with numbers from 1 to 10</span></span>
<span id="cb81-5"><a href="working-with-data.html#cb81-5"></a>x &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">10</span></span>
<span id="cb81-6"><a href="working-with-data.html#cb81-6"></a><span class="co"># keep only numbers &lt; 5:</span></span>
<span id="cb81-7"><a href="working-with-data.html#cb81-7"></a><span class="co">#   (i) without %&lt;&gt;%</span></span>
<span id="cb81-8"><a href="working-with-data.html#cb81-8"></a>x &lt;-<span class="st"> </span>x[x<span class="op">&lt;</span><span class="dv">5</span>]</span>
<span id="cb81-9"><a href="working-with-data.html#cb81-9"></a><span class="co">#   (i) with %&lt;&gt;%</span></span>
<span id="cb81-10"><a href="working-with-data.html#cb81-10"></a>x <span class="op">%&lt;&gt;%</span><span class="st"> </span>.[.<span class="op">&lt;</span><span class="dv">5</span>]</span></code></pre></div>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="working-with-data.html#cb82-1"></a><span class="co"># lets add several columns to &#39;dativeSimplified&#39;</span></span>
<span id="cb82-2"><a href="working-with-data.html#cb82-2"></a>dativeSimplified <span class="op">%&lt;&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">A=</span><span class="dv">1</span>, <span class="dt">B=</span><span class="dv">2</span>, <span class="dt">C=</span><span class="dv">3</span>, <span class="dt">D=</span><span class="dv">4</span>)</span>
<span id="cb82-3"><a href="working-with-data.html#cb82-3"></a><span class="kw">head</span>(dativeSimplified)</span></code></pre></div>
<pre class="r-output"><code>##   RealizationOfRec  Verb AnimacyOfRec AnimacyOfTheme LengthOfTheme
## 1               NP  feed      animate      inanimate      2.639057
## 2               NP  give      animate      inanimate      1.098612
## 3               NP  give      animate      inanimate      2.564949
## 4               NP  give      animate      inanimate      1.609438
## 5               NP offer      animate      inanimate      1.098612
## 6               NP  give      animate      inanimate      1.386294
##   is_realization_NP A B C D
## 1              TRUE 1 2 3 4
## 2              TRUE 1 2 3 4
## 3              TRUE 1 2 3 4
## 4              TRUE 1 2 3 4
## 5              TRUE 1 2 3 4
## 6              TRUE 1 2 3 4</code></pre>
</div>
</div>
<div id="functions-used-in-this-section" class="section level2">
<h2><span class="header-section-number">4.4</span> Functions used in this section</h2>
<div id="operators-2" class="section level3">
<h3><span class="header-section-number">4.4.1</span> Operators</h3>
<div class="function">
<p><code>%&gt;%</code></p>
<p><em>(Forward) pipe:</em> Use the expression on the left as a part of the expression on the right.</p>
<ul>
<li>Read <code>x %&gt;% fn</code> as <em>‘use <code>x</code> as the <strong>only</strong> argument of function <code>fn</code>’.</em></li>
<li>Read <code>x %&gt;% fn(1, 2)</code> as <em>‘use <code>x</code> as the <strong>first</strong> argument of function <code>fn</code>’.</em></li>
<li>Read <code>x %&gt;% fn(1, ., 2)</code> as <em>‘use <code>x</code> as the <strong>second</strong> argument of function <code>fn</code>’.</em></li>
</ul>
</div>
<br>
<div class="function">
<p><code>%&lt;&gt;%</code></p>
<p><em>Assignment pipe:</em> Use the expression on the left as a part of the expression on the right, <strong>and assign the result back to the left part of the expression</strong>.</p>
<ul>
<li><code>x %&lt;&gt;% ...</code> is equivalent to <code>x &lt;- x %&gt;% ...</code></li>
<li>Read <code>x %&lt;&gt;% fn</code> as <em>‘use <code>x</code> as the <strong>only</strong> argument of function <code>fn</code>, <strong>and assign it the result to x</strong>’.</em></li>
<li>Read <code>x %&lt;&gt;% fn(1, 2)</code> as <em>‘use <code>x</code> as the <strong>first</strong> argument of function <code>fn</code>, <strong>and assign it the result to x</strong>’.</em></li>
<li>Read <code>x %&lt;&gt;% fn(1, ., 2)</code> as <em>‘use <code>x</code> as the <strong>second</strong> argument of function <code>fn</code>, <strong>and assign it the result to x</strong>’.</em></li>
</ul>
</div>
<br>
<div class="function">
<p><code>df[selected_rows, indices_columns]</code></p>
<p><em>Indexing operator:</em> Accesses specific rows and/or columns of a data frame.</p>
<ul>
<li><code>selected_rows</code> A vector of indices or names.</li>
<li><code>selected_columns</code> A vector of indices or names.</li>
</ul>
</div>
<br>
<div class="function">
<p><code>::</code></p>
<p><em>Double colon operator:</em> Accesses functions and other objects from packages. Read <code>x::y</code> as <em>‘y from package x.’</em></p>
</div>
<p><br></p>
</div>
<div id="functions-1" class="section level3">
<h3><span class="header-section-number">4.4.2</span> Functions</h3>
<div class="function">
<p><code>help(name)</code></p>
<p>Displays the documentation for an object, such as a function or data frame in R.</p>
<ul>
<li><code>object</code> Must be a function or data frame currently loaded in R. If the package in which the function or dataset are located is not currently loaded, the name must be specified using the double-colon operator, i.e., as <code>package::name</code>. For example, <code>help('dplyr::summarize')</code>.</li>
</ul>
</div>
<br>
<div class="function">
<p><code>ifelse(condition, val_if_cond_true, val_if_cond_false)</code></p>
<p>Replaces all occurrences of <code>TRUE</code> by <code>val_if_cond_true</code>, and all occurrences of <code>FALSE</code> by <code>val_if_cond_false</code> and returns the resulting vector.</p>
<ul>
<li>If <code>val_if_cond_true</code> and <code>val_if_cond_false</code> are vectors, the elements of condition at every index <span class="math inline">\(i\)</span> are replaces by <code>val_if_cond_true[i]</code> and <code>val_if_cond_false[i]</code>, respectively.</li>
</ul>
</div>
<br>
<div class="function">
<p><code>unique(object)</code></p>
<p>Return only the unique values in an object. That is, return each value that occurs in vector or data frame object exactly once. For vectors, this means <em>unique values</em>. For data frames, this means <em>unique rows</em>.</p>
<ul>
<li><code>object</code> A vector, matrix, or data frame.</li>
</ul>
</div>
<br>
<div class="function">
<p><code>nrow(object)</code></p>
<p>Return the number of rows in <code>object</code>.</p>
<ul>
<li><code>object</code> A data frame or matrix.</li>
</ul>
</div>
<br>
<div class="function">
<p><code>ncol(object)</code></p>
<p>Return the number of columns in <code>object</code>.</p>
<ul>
<li><code>object</code> A data frame or matrix.</li>
</ul>
</div>
<br>
<div class="function">
<p><code>sample(vector, size = length(vector), replace = FALSE)</code></p>
<p>Select a number of random elements from <code>vector</code>. If <code>size == length(vector)</code>, the vector is just returned in randomly permuted order.</p>
<ul>
<li><code>vector</code> The vector from which to sample.</li>
<li><code>size</code> How many elements to sample. Must be smaller than or equal to the length of <code>vector</code>, which is the default.</li>
<li><code>replace</code> Logical. Sample with replacement? (i.e., Can the same element be sampled several times?) Defaults to <code>FALSE</code>.</li>
</ul>
</div>
<p><br></p>
<div class="function">
<p><code>group_by(df, grouping_var1, ...)</code></p>
<p>Records the grouping of a data frame for future application of <code>summarize()</code> or <code>mutate()</code>.</p>
<ul>
<li><code>df</code> A data frame.</li>
<li><code>grouping_var1</code> The first grouping variable.</li>
<li><code>...</code> More grouping variables, if applicable.</li>
</ul>
</div>
<p><br></p>
<div class="function">
<p><code>summarize(df, expression1, ...)</code></p>
<p>Computes a series of summary statistics for each combination of values specified by the levels of the grouping variables, for example compute the average of a column.</p>
<ul>
<li><code>df</code> A data frame, typically previously grouped using <code>group_by</code>.</li>
<li><code>expression1</code> An expression computing a summary statistics.</li>
<li><code>...</code> An expression computing summary statistics.</li>
</ul>
</div>
<p><br></p>
<div class="function">
<p><code>mutate(df, expression1, ...)</code></p>
<p>Modify and old column, or create a new one for each combination of grouping variable levels.</p>
<ul>
<li><code>df</code> A data frame, typically previously grouped using <code>group_by</code>.</li>
<li><code>expression1</code> An expression creating a new column, or modifying an old one.</li>
<li><code>...</code> More expressions creating new columns, or modifying an old ones.</li>
</ul>
</div>
<br>
<div class="function">
<p><code>n()</code></p>
<p>Within a call to <code>summarize()</code> or <code>mutate()</code>, <code>n()</code> computes the number of rows at each combination of grouping variable levels.</p>
</div>
<p><br></p>
<div class="function">
<p><code>arrange()</code></p>
</div>
<br>
<div class="function">
<p><code>select()</code></p>
</div>
<br>
<div class="function">
<p><code>sample_n()</code></p>
</div>
<p><br></p>
<!-- to-do:
- Explain what the point of the group_by/mutate combo is.
- Introduce the $ operator together with data frames
-->

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="introR.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="a-first-plot.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["LectureNotes.pdf", "LectureNotes.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
